"""Make _password_hash nullable

Revision ID: 3499b67ecc5b
Revises: b0dcc8e18c05
Create Date: 2025-07-02 13:25:50.939510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3499b67ecc5b'
down_revision = 'b0dcc8e18c05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('_password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
